/**
 * Provides US Census Bureau export data to EU27 as liveData entries
 * compatible with the Comext hook shape used by V4App.
 *
 * Data source: src/data/censusTrade.js
 *   Generated by:  node scripts/build_census_trade.mjs
 *   Fetched from:  Census Bureau via fetch_us_trade_raw.py
 *
 * The static file contains monthly metric tonnes keyed by TRADE id.
 * Each entry is a direct monthly value — no distribution needed.
 * 2026 confirmed months (where Census has published data) are included
 * and drive the "Confirmed exposure" view in V4App.
 *
 * Returns { liveData: { entries, gotAny }, fetchStatus }.
 * No browser network requests are made.
 */

import { useMemo } from "react";
import { CENSUS_EU27_EXPORTS } from "../data/censusTrade.js";

/**
 * Build liveData entries from the static Census monthly data.
 * entries[tradeKey][ym] = [monthlyTonnes, 0]
 */
function buildEntries() {
  const entries = {};
  for (const [key, byYm] of Object.entries(CENSUS_EU27_EXPORTS)) {
    entries[key] = {};
    for (const [ym, tonnes] of Object.entries(byYm)) {
      entries[key][ym] = [tonnes, 0];
    }
  }
  return entries;
}

// Build once at module load — no async needed, data is static.
const CENSUS_ENTRIES = buildEntries();
const GOT_ANY = Object.keys(CENSUS_ENTRIES).length > 0;

export function useUSCensusData() {
  const result = useMemo(() => ({
    liveData: { entries: CENSUS_ENTRIES, gotAny: GOT_ANY },
    fetchStatus: GOT_ANY ? "done" : "fallback",
  }), []);

  return result;
}
